# ==============================
# Minimal config for testing
# ==============================

# 数据相关
batch_size: 8           # 小批次，减少内存占用
epochs: 1               # 只训练 1 个 epoch，快速跑完
learning_rate: 0.01     # 较大学习率，加快收敛速度

# 模型结构
model:
  hidden_units: 16      # 极小的隐藏层单元数
  dropout: 0.1          # 轻微 dropout，保持逻辑完整

# 其他设置
validation_split: 0.2   # 使用 20% 数据做验证
