# 数据来源配置
data:
  type: web     # 可选值: "web" | "local"
  url: "http://localhost:5000/api/game2048"

# 模型配置
model:
  class: models.model.Game2048Model
  params:
    input_dim: 16
    hidden_dim: 128
    output_dim: 4

# 训练配置
train:
  class: train.train.Trainer
  params:
    epochs: 100
    batch_size: 32
    learning_rate: 0.001
